apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemo-deployment
spec:
  selector:
    matchLabels:
      app: nginxdemo
  replicas: 6
  template:
    metadata:
      labels:
        app: nginxdemo
    spec:
      containers:
        - name: nginxdemo
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
